#! /bin/sh
#
# This File is part of the Freemol package
# (C) 2003 Fabio Mariotti, <fabio.mariotti@scriptsforscience.org>
# Please read the full copyright statment in the COPYING file
########################################################################
# Scan directory tree to find the target compiler
# Author: F.Mariotti <fabio.mariotti@unifr.ch>
# Version: 0.1 - Aug 2000
# Bugs: works only if it run in the config directory
#       and if the dir structure is well suited
########################################################################
# $Id: getcompilers,v 1.1.1.1 2009/01/12 16:56:08 mariotti Exp $
########################################################################
#
# Need one argument
#
if test -z $1
then
  echo " One argument required "
  exit 1;
fi;
#
mfiles=`find $1 -name 'Make.*' -exec basename \{\} \;`
cline=" "
for tcomp in $mfiles ;
do
  cname=`echo $tcomp | awk -F \. '{print $2}'`
  cline="$cline $cname"
done;
echo $cline
#
